In [60]:
import numpy as np
import pandas as pd
import torch

## PART NUMPY

In [61]:
LIST = [10, 20, 30, 40]
LIST

[10, 20, 30, 40]

### Q1
1. แปลง list เป็น ndarray โดยการใช้คำสั่ง `np.array(LIST)`

In [62]:
ans_1 = np.array(LIST)
ans_1

array([10, 20, 30, 40])

### Q2
1. shape จากข้อ 1 ยังไม่ตรง (1, 4) เลยต้องใช้ `.reshape((shape))` เพื่อให้ shape ตรง (2, 2)
2. จากนั้นทำการ - แบบ element wise
3. จากนั้นทำการ สร้าง random ndarray ด้วย `np.random.random((shape))`

In [63]:
np.random.seed(42)

In [64]:
ans_2 = ans_1.reshape((2, 2)) - 5 * np.array([[1, 1], [1, 1]]) - np.random.random((2, 2))
ans_2

array([[ 4.62545988, 14.04928569],
       [24.26800606, 34.40134152]])

### Q3
1. ทำการ slicing ด้วย `[:, 0]` (: หมายถึงทั้งหมด)
2. ทำการต่อด้วยการ `np.concat([arr1, arr2, ... arr3], dim=0)` (dim=0 คือชั้นนอกสุด)

In [65]:
ans_3 = ans_2[: , 0]
ans_3 = ans_3.reshape((2, 1))
ans_3 = np.concat([ans_3, ans_3], axis=0)
ans_3

array([[ 4.62545988],
       [24.26800606],
       [ 4.62545988],
       [24.26800606]])

## PART PYTORCH

### Q4
1. ทำการสร้าง tensor ด้วยคำสั่ง `torch.tensor(LIST)`

In [66]:
ans_4 = torch.tensor(LIST)
ans_4

tensor([10, 20, 30, 40])

### Q5
1. ทำการแปลง shape ด้วยคำสั่ง `.reshape(shape)`
2. ทำการลบแบบ element wise กับ random tensor จากคำสั่ง `torch.rand((shape))`

In [67]:
torch.manual_seed(42)

In [68]:
ans_5 = ans_4.reshape(2, 2)
ans_5 = ans_5 - 2 * torch.tensor([[1, 0], [0, 1]]) + torch.rand((2, 2))
ans_5

tensor([[ 8.8823, 20.9150],
        [30.3829, 38.9593]])

### Q6
1. slice ด้วย `[1, :]` (: คือทั้งหมด)
2. ทำการต่อ tensor ด้วย `torch.cat((tensor1, tensor2, ..., tensorn), dim=0)`

In [69]:
ans_6 = ans_5[1, :]
ans_6 = torch.cat((ans_6, ans_6), dim=0)
ans_6

tensor([30.3829, 38.9593, 30.3829, 38.9593])

### Q7
1. ทำการแปลง ans_3 เป็น tensor ด้วย `torch.tensor(ndarray, dtype=float)`
2. reshape ให้ทำการ matmul ได้
2. ทำการ mat mul ด้วย operator `@`

In [ ]:
ans_7 = torch.tensor(ans_3, dtype=torch.float64)
ans_6_2d = ans_6.reshape(1, 4)
ans_7 = ans_7 @ ans_6_2d.double()
ans_7

tensor([[140.5347, 180.2047, 140.5347, 180.2047],
        [737.3315, 945.4646, 737.3315, 945.4646],
        [140.5347, 180.2047, 140.5347, 180.2047],
        [737.3315, 945.4646, 737.3315, 945.4646]], dtype=torch.float64)

### Q8
1. แสดงผลลัพธ์ของทุกข้อและทำการแสดง shape ของทุกข้อ

In [71]:
print(f"Ans 1      :\n{ans_1}")
print(f"Ans 1 Shape:\n{ans_1.shape}")
print("=" * 50)
print(f"Ans 2      :\n{ans_2}")
print(f"Ans 2 Shape:\n{ans_2.shape}")
print("=" * 50)
print(f"Ans 3      :\n{ans_3}")
print(f"Ans 3 Shape:\n{ans_3.shape}")
print("=" * 50)
print(f"Ans 4      :\n{ans_4}")
print(f"Ans 4 Shape:\n{ans_4.shape}")
print("=" * 50)
print(f"Ans 5      :\n{ans_5}")
print(f"Ans 5 Shape:\n{ans_5.shape}")
print("=" * 50)
print(f"Ans 6      :\n{ans_6}")
print(f"Ans 6 Shape:\n{ans_6.shape}")
print("=" * 50)
print(f"Ans 7      :\n{ans_7}")
print(f"Ans 7 Shape:\n{ans_7.shape}")
print("=" * 50)

Ans 1      :
[10 20 30 40]
Ans 1 Shape:
(4,)
Ans 2      :
[[ 4.62545988 14.04928569]
 [24.26800606 34.40134152]]
Ans 2 Shape:
(2, 2)
Ans 3      :
[[ 4.62545988]
 [24.26800606]
 [ 4.62545988]
 [24.26800606]]
Ans 3 Shape:
(4, 1)
Ans 4      :
tensor([10, 20, 30, 40])
Ans 4 Shape:
torch.Size([4])
Ans 5      :
tensor([[ 8.8823, 20.9150],
        [30.3829, 38.9593]])
Ans 5 Shape:
torch.Size([2, 2])
Ans 6      :
tensor([30.3829, 38.9593, 30.3829, 38.9593])
Ans 6 Shape:
torch.Size([4])
Ans 7      :
tensor([[140.5347, 180.2047, 140.5347, 180.2047],
        [737.3315, 945.4646, 737.3315, 945.4646],
        [140.5347, 180.2047, 140.5347, 180.2047],
        [737.3315, 945.4646, 737.3315, 945.4646]], dtype=torch.float64)
Ans 7 Shape:
torch.Size([4, 4])
